name: Archive Model
on:
  push:
    tags:
    - model*

jobs:
  archive-model:
    name: Archive Model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: >-
        python -m pip install --upgrade pip==20.2
        pip install -r Rasa_Bot/requirements.txt
        pip install yq
    - name: Read max history
      run: >-
        echo "MAX_HISTORY=$(yq -r .policies.max_history ./Rasa_Bot/config.yml)" >> $GITHUB_ENV
    - name: Rasa Data Validation
      run: >-
        cd Rasa_Bot
        rasa telemetry disable
        rasa data validate --max-history ${{ env.MAX_HISTORY }} --domain domain/
        rasa train --domain domain/
        rasa test core --stories tests/test_conversations.yml --fail-on-prediction-errors
    - uses: actions/upload-artifact@master
      with:
        name: model
        path: Rasa_Bot/models
