name: Rasa CI

on:
  # Trigger analysis when pushing in master or pull requests, and when creating
  # a pull request.
  push:
    branches:
      - main
  pull_request:
      types: [opened, synchronize, reopened]

jobs:
  # Validate the Rasa data, e.g. check whether the same example
  # is used for 2 different intents, etc.
  data-validation:
    name: Validate Data
    runs-on: ubuntu-latest
    env:
      working-directory: ./Rasa_Bot
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==20.2
        pip install -r Rasa_Bot/requirements.txt
    # The number for max-history needs to be adapted based on config.yml
    - name: Rasa Data Validation
      run: | 
        cd Rasa_Bot
        rasa telemetry disable
        rasa data validate --max-history 10 --domain domain/
  training-testing:
    name: Train and Test model
    runs-on: ubuntu-latest
    needs: 
    - data-validation
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==20.2
        pip install -r Rasa_Bot/requirements.txt
        rasa --version
    - name: Train model
      run: |
        cd Rasa_Bot
        rasa train --domain domain/
    - name: Test End 2 End Stories
      run: |
        cd Rasa_Bot
        rasa --version
        rasa test core --stories tests/test_conversations.yml --fail-on-prediction-errors
    # In the future, we could also save the trained model in github
    # See here for an example: https://github.com/RasaHQ/financial-demo/blob/db/.github/workflows/build_and_deploy.yml
   
